version: '3.7'

x-networks: &networks
  - content-net
  - courses-net
  - lab-net

services:
  caddy:
    container_name: saurons_proxy
    image: 'caddy:latest'
    networks: *networks
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./config/caddy-config:/config
      - ./config/caddy-data:/data
      - ./Caddyfile:/etc/caddy/Caddyfile

networks:
  content-net:
    external: true
    name: content_net
  courses-net:
    external: true
    name: courses_net
  lab-net:
    external: true
    name: lab_net
