version: '3.7'

x-networks:
  &networks
  - archive-net
  - content-net
  - courses-net
  - lab-net

services:
  caddy:
    container_name: saurons_proxy
    image: 'caddy:latest'
    networks: *networks
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./config/caddy-config:/config
      - ./config/caddy-data:/data
      - ./Caddyfile:/etc/caddy/Caddyfile

  adminer:
    container_name: saurons_adminer
    image: gpalab/adminer
    networks: *networks
    environment:
      ADMINER_DEFAULT_SERVER: content_db
    expose:
      - '8080'

networks:
  archive-net:
    external: true
    name: archive_net
  content-net:
    external: true
    name: content_net
  courses-net:
    external: true
    name: courses_net
  lab-net:
    external: true
    name: lab_net
