remote_theme: IIP-Design/lab-notes

title: GPA Lab Tools
author: Bureau of Global Public Affairs (GPA) Digital Lab Team
author_homepage: https://github.com/IIP-Design
repository: IIP-Design/lab-tools
description: Development and build tooling for the U.S. Department of State's, Global Public Affairs Digital Lab.
logo: assets/flask.png
show_downloads: false
show_nav: true

collections:
  dev_meetings:
    output: true
  presentations:
    output: true

defaults:
  - scope:
      path: ""
      type: dev_meetings
    values:
      layout: post
      image: /assets/dev-meeting-cover.png
      image_credit: Photo by Yancy Min on Unsplash
      toc: true
  - scope:
      path: ""
      type: presentations
    values:
      layout: presentation

markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true

port: 4040
